### PR TITLE
Added "keyboard" mode and four column option (with minus & enter)

### PR DESCRIPTION
**Pull request by unverbraucht**
For my finance app I needed a keyboard that could enter signed decimal numbers but act like the system keyboard since I had multiple edit texts in a list and didn't want to have fixed numpad views in there.

I liked your library so I extended it with a new keyboard type, the 4 column (I needed the room for the sign change). I have attached a screenshot for you. It uses it's own layout file and all existing modes work without change.
device-2018-08-15-172753

I also needed a way to show the numpad instead of the keyboard. I opted for opening the IME first and then overlaying it with the numpad. The downside is that the first time that the IME opens it is visible for a split second (we need it to open to get it's height). The upsides are that the back button becomes the "down button" as with a real IME, and that the height of the numpad is correct. The code for the popup is loosely based on [https://github.com/vanniktech/Emoji](url) (will push some more attribution into the source with the next commit).

I've added a new sample Activity to showcase the new stuff.

### CODE REVIEW

**Comment by unverbraucht** [comment]
Attribution added, and I've updated the README.MD

**Comment by davidmigloz** [comment]
Hi Kevin, thank you very much for the PR 😃
I'll review it in the next couple of days.
Cheers!

**Comment by unverbraucht** [comment]
Hi David, you're very welcome, thanks for the nice project :) I pushed a small fix.

**Comment by davidmigloz** [comment]
I'm having a pretty busy week... but I haven't forgotten your PRs :) Sorry for the delay!

**Comment by unverbraucht** [comment]
No worries :) I had to merge the branch for the second PR into master because there was so much overlap between both, so I’m afraid currently it’s an all-or-nothing situation. If you want to have the popup without the 4 column mode I’ll look into cherry-picking or separating the code manually.

**Comment by adamski** [comment]
Thanks for this, I need the 4 column view for my app, any chance this could be merged or at least conflicts resolved?

**Comment by davidmigloz** [comment]
This PR never made it to main unfortunately (my bad).
The library has now been migrated to compose, so I'll close it.

**Pull request closed without merging**
